-- ============================================
-- STUDYBUD COMPLETE DATABASE SCHEMA
-- ============================================
-- Run this entire file in Supabase SQL Editor
-- This creates all tables for: Habits, Study, Mind, and Focus modules
-- ============================================

-- ============================================
-- 1. HABITS MODULE (Atom System)
-- ============================================

create table if not exists atoms (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text not null,
  frequency text not null, -- 'daily', 'weekly'
  category text, -- 'health', 'study', 'mind'
  fission_entry text, -- The 2-minute version
  user_id uuid references auth.users not null
);

create table if not exists logs (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  atom_id bigint references atoms(id) on delete cascade not null,
  date_logged date not null,
  status text not null, -- 'completed', 'skipped'
  user_id uuid references auth.users not null,
  unique(atom_id, date_logged)
);

-- ============================================
-- 2. STUDY MODULE
-- ============================================

create table if not exists study_techniques (
  id bigint generated by default as identity primary key,
  name text not null,
  category text not null, -- 'memory', 'understanding', 'practice', 'organization'
  description text not null,
  why_it_works text,
  when_to_use text,
  time_needed text,
  difficulty text default 'easy',
  effectiveness_rating int default 5
);

create table if not exists study_subjects (
  id bigint generated by default as identity primary key,
  name text not null unique,
  icon text,
  strategies jsonb,
  color text default '#74b9ff'
);

create table if not exists study_assignments (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  user_id uuid references auth.users not null,
  title text not null,
  subject text,
  deadline timestamp with time zone,
  steps jsonb,
  status text default 'not_started',
  notes text
);

create table if not exists study_practice_logs (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  user_id uuid references auth.users not null,
  subject text not null,
  mistake_type text,
  question_content text,
  notes text,
  tags text[]
);

create table if not exists study_reviews (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  user_id uuid references auth.users not null,
  content text not null,
  subject text,
  next_review_date timestamp with time zone not null,
  interval_days int default 1,
  review_count int default 0
);

-- ============================================
-- 3. MIND MODULE (Mental Health)
-- ============================================

create table if not exists mind_logs (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  user_id uuid references auth.users not null,
  type text not null, -- 'chat', 'meditation', 'reflection', 'offload'
  content jsonb,
  emotional_state_before text,
  emotional_state_after text,
  tags text[]
);

create table if not exists mind_offload_items (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  user_id uuid references auth.users not null,
  content text not null,
  bucket_category text not null, -- 'Worry', 'Conflict', 'Regret', 'What-If'
  is_archived boolean default false,
  is_resolved boolean default false
);

create table if not exists mind_wins (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  user_id uuid references auth.users not null,
  content text not null,
  impact_score int default 1,
  type text default 'micro_win'
);

-- ============================================
-- 4. FOCUS MODULE (Time Management)
-- ============================================

create table if not exists tasks (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  user_id uuid references auth.users,
  title text not null,
  description text,
  cognitive_type text not null,
  difficulty text not null,
  time_estimate int not null,
  emotional_friction text not null,
  status text default 'Planned',
  energy_block text,
  actual_time int,
  mood text,
  execution_quality text,
  notes text
);

-- ============================================
-- 5. ROW LEVEL SECURITY (RLS)
-- ============================================

-- Habits
alter table atoms enable row level security;
alter table logs enable row level security;

create policy "Users can view their own atoms" on atoms for select using (auth.uid() = user_id);
create policy "Users can insert their own atoms" on atoms for insert with check (auth.uid() = user_id);
create policy "Users can update their own atoms" on atoms for update using (auth.uid() = user_id);
create policy "Users can delete their own atoms" on atoms for delete using (auth.uid() = user_id);

create policy "Users can view their own logs" on logs for select using (auth.uid() = user_id);
create policy "Users can insert their own logs" on logs for insert with check (auth.uid() = user_id);
create policy "Users can update their own logs" on logs for update using (auth.uid() = user_id);

-- Study
alter table study_assignments enable row level security;
alter table study_practice_logs enable row level security;
alter table study_reviews enable row level security;

create policy "Users can view their own assignments" on study_assignments for select using (auth.uid() = user_id);
create policy "Users can insert their own assignments" on study_assignments for insert with check (auth.uid() = user_id);
create policy "Users can update their own assignments" on study_assignments for update using (auth.uid() = user_id);
create policy "Users can delete their own assignments" on study_assignments for delete using (auth.uid() = user_id);

create policy "Users can view their own practice logs" on study_practice_logs for select using (auth.uid() = user_id);
create policy "Users can insert their own practice logs" on study_practice_logs for insert with check (auth.uid() = user_id);

create policy "Users can view their own reviews" on study_reviews for select using (auth.uid() = user_id);
create policy "Users can insert their own reviews" on study_reviews for insert with check (auth.uid() = user_id);
create policy "Users can update their own reviews" on study_reviews for update using (auth.uid() = user_id);

-- Mind
alter table mind_logs enable row level security;
alter table mind_offload_items enable row level security;
alter table mind_wins enable row level security;

create policy "Users can view their own mind logs" on mind_logs for select using (auth.uid() = user_id);
create policy "Users can insert their own mind logs" on mind_logs for insert with check (auth.uid() = user_id);

create policy "Users can view their own offload items" on mind_offload_items for select using (auth.uid() = user_id);
create policy "Users can insert their own offload items" on mind_offload_items for insert with check (auth.uid() = user_id);
create policy "Users can update their own offload items" on mind_offload_items for update using (auth.uid() = user_id);

create policy "Users can view their own wins" on mind_wins for select using (auth.uid() = user_id);
create policy "Users can insert their own wins" on mind_wins for insert with check (auth.uid() = user_id);

-- Focus (Tasks)
alter table tasks enable row level security;

create policy "Anyone can view tasks" on tasks for select using (true);
create policy "Users can insert their own tasks" on tasks for insert with check (auth.uid() = user_id OR user_id IS NULL);
create policy "Users can update their own tasks" on tasks for update using (auth.uid() = user_id OR user_id IS NULL);
create policy "Users can delete their own tasks" on tasks for delete using (auth.uid() = user_id OR user_id IS NULL);

-- ============================================
-- 7. USER PROFILES
-- ============================================

create table if not exists profiles (
  id uuid references auth.users on delete cascade primary key,
  first_name text,
  last_name text,
  nickname text,
  age int,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table profiles enable row level security;

create policy "Users can view their own profile" on profiles for select using (auth.uid() = id);
create policy "Users can insert their own profile" on profiles for insert with check (auth.uid() = id);
create policy "Users can update their own profile" on profiles for update using (auth.uid() = id);

-- ============================================
-- 8. FOCUS SESSIONS
-- ============================================

create table if not exists focus_sessions (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  user_id uuid references auth.users not null,
  category text,
  duration_seconds int,
  mode text
);

alter table focus_sessions enable row level security;

create policy "Users can view their own focus sessions" on focus_sessions for select using (auth.uid() = user_id);
create policy "Users can insert their own focus sessions" on focus_sessions for insert with check (auth.uid() = user_id);

-- ============================================
-- 9. PUBLIC TABLES (Read-only for all)
-- ============================================
-- ... existing code ...

-- Study techniques and subjects are public reference data
alter table study_techniques enable row level security;
alter table study_subjects enable row level security;

create policy "Anyone can view study techniques" on study_techniques for select using (true);
create policy "Anyone can view study subjects" on study_subjects for select using (true);
