-- Mental Health Module Schema

-- 1. General Mind Logs (Chats, Meditations, Reflections)
create table mind_logs (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  user_id uuid references auth.users not null,
  type text not null, -- 'chat', 'meditation', 'reflection', 'offload'
  content jsonb, -- Stores the chat transcript, reflection answers, etc.
  emotional_state_before text, -- 'Anxious', 'Calm', etc.
  emotional_state_after text,
  tags text[] -- ['academic', 'family', 'self-worth']
);

-- 2. Cognitive Offload Items (The Bucket System)
create table mind_offload_items (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  user_id uuid references auth.users not null,
  content text not null,
  bucket_category text not null, -- 'Worry', 'Conflict', 'Regret', 'What-If'
  is_archived boolean default false,
  is_resolved boolean default false
);

-- 3. Wins & Meaning (Positive Affect)
create table mind_wins (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  user_id uuid references auth.users not null,
  content text not null,
  impact_score int default 1, -- 1-5 scale
  type text default 'micro_win' -- 'micro_win', 'meaning_moment'
);

-- RLS Policies
alter table mind_logs enable row level security;
alter table mind_offload_items enable row level security;
alter table mind_wins enable row level security;

create policy "Users can view their own mind logs" on mind_logs for select using (auth.uid() = user_id);
create policy "Users can insert their own mind logs" on mind_logs for insert with check (auth.uid() = user_id);

create policy "Users can view their own offload items" on mind_offload_items for select using (auth.uid() = user_id);
create policy "Users can insert their own offload items" on mind_offload_items for insert with check (auth.uid() = user_id);
create policy "Users can update their own offload items" on mind_offload_items for update using (auth.uid() = user_id);

create policy "Users can view their own wins" on mind_wins for select using (auth.uid() = user_id);
create policy "Users can insert their own wins" on mind_wins for insert with check (auth.uid() = user_id);
