-- Create a table for Atoms (Habits)
create table atoms (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text not null,
  frequency text not null, -- 'daily', 'weekly'
  category text, -- 'health', 'study', 'mind'
  user_id uuid references auth.users not null
);

-- Create a table for Logs (Tracking execution)
create table logs (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  atom_id bigint references atoms(id) on delete cascade not null,
  date_logged date not null,
  status text not null, -- 'completed', 'skipped'
  user_id uuid references auth.users not null,
  unique(atom_id, date_logged)
);

-- Enable Row Level Security (RLS)
alter table atoms enable row level security;
alter table logs enable row level security;

-- Create policies
create policy "Users can view their own atoms" on atoms
  for select using (auth.uid() = user_id);

create policy "Users can insert their own atoms" on atoms
  for insert with check (auth.uid() = user_id);

create policy "Users can update their own atoms" on atoms
  for update using (auth.uid() = user_id);

create policy "Users can view their own logs" on logs
  for select using (auth.uid() = user_id);

create policy "Users can insert their own logs" on logs
  for insert with check (auth.uid() = user_id);

create policy "Users can update their own logs" on logs
  for update using (auth.uid() = user_id);
