-- COMPLETE DATABASE SETUP SCRIPT
-- Run this entire script in your Supabase SQL Editor.

-- 1. Create the 'atoms' table (Habits)
create table if not exists atoms (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text not null,
  frequency text not null default 'daily',
  category text default 'study',
  fission_entry text,
  notes text,
  user_id uuid references auth.users -- Nullable for now
);

-- 2. Create the 'logs' table (Tracking)
create table if not exists logs (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  atom_id bigint references atoms(id) on delete cascade not null,
  date_logged date not null,
  status text not null,
  user_id uuid references auth.users, -- Nullable for now
  unique(atom_id, date_logged)
);

-- 3. Disable Security Policies for Development
-- This ensures you can save data without debugging login/auth right now.
alter table atoms disable row level security;
alter table logs disable row level security;

-- 4. (Optional) Security Policies (Commented out for now)
-- You will enable these later when you add a Login screen.
-- alter table atoms enable row level security;
-- create policy "Users can view own atoms" on atoms for select using (auth.uid() = user_id);
-- ...
