-- Study Module Schema (Enhanced)

-- 1. Study Techniques Library (Comprehensive)
create table study_techniques (
  id bigint generated by default as identity primary key,
  name text not null,
  category text not null, -- 'memory', 'understanding', 'practice', 'organization'
  description text not null,
  why_it_works text,
  when_to_use text,
  time_needed text, -- '5-10 min', '30 min', etc.
  difficulty text default 'easy', -- 'easy', 'medium', 'hard'
  effectiveness_rating int default 5 -- 1-10 scale
);

-- 2. Subjects & Strategies
create table study_subjects (
  id bigint generated by default as identity primary key,
  name text not null unique,
  icon text,
  strategies jsonb,
  color text default '#74b9ff'
);

-- 3. User Assignments
create table study_assignments (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  user_id uuid references auth.users not null,
  title text not null,
  subject text,
  deadline timestamp with time zone,
  steps jsonb,
  status text default 'not_started',
  notes text
);

-- 4. Practice Logs
create table study_practice_logs (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  user_id uuid references auth.users not null,
  subject text not null,
  mistake_type text,
  question_content text,
  notes text,
  tags text[]
);

-- 5. Review Schedule
create table study_reviews (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  user_id uuid references auth.users not null,
  content text not null,
  subject text,
  next_review_date timestamp with time zone not null,
  interval_days int default 1,
  review_count int default 0
);

-- RLS Policies
alter table study_assignments enable row level security;
alter table study_practice_logs enable row level security;
alter table study_reviews enable row level security;

create policy "Users can view their own assignments" on study_assignments for select using (auth.uid() = user_id);
create policy "Users can insert their own assignments" on study_assignments for insert with check (auth.uid() = user_id);
create policy "Users can update their own assignments" on study_assignments for update using (auth.uid() = user_id);
create policy "Users can delete their own assignments" on study_assignments for delete using (auth.uid() = user_id);

create policy "Users can view their own practice logs" on study_practice_logs for select using (auth.uid() = user_id);
create policy "Users can insert their own practice logs" on study_practice_logs for insert with check (auth.uid() = user_id);

create policy "Users can view their own reviews" on study_reviews for select using (auth.uid() = user_id);
create policy "Users can insert their own reviews" on study_reviews for insert with check (auth.uid() = user_id);
create policy "Users can update their own reviews" on study_reviews for update using (auth.uid() = user_id);

-- Seed Data: Comprehensive Study Techniques
insert into study_techniques (name, category, description, why_it_works, when_to_use, time_needed, difficulty, effectiveness_rating) values
-- Memory Techniques
('Active Recall', 'memory', 'Close your notes and try to write down everything you remember from scratch.', 'Forcing retrieval strengthens neural pathways more than passive review.', 'After reading a chapter or watching a lecture.', '10-15 min', 'easy', 9),
('Spaced Repetition', 'memory', 'Review material at increasing intervals: 1 day, 3 days, 7 days, 14 days, 30 days.', 'Spacing fights the forgetting curve. Your brain remembers better when forced to retrieve over time.', 'For anything you need to remember long-term.', 'Ongoing', 'medium', 10),
('Blurting', 'memory', 'Set a timer for 5 minutes. Write everything you know about a topic without looking at notes.', 'Active retrieval without cues. Shows you what you actually know vs. what you think you know.', 'Before exams or after studying a topic.', '5-10 min', 'easy', 8),
('Memory Palace', 'memory', 'Visualize a familiar place and mentally place information at specific locations.', 'Spatial memory is powerful. Linking abstract info to physical spaces aids recall.', 'For memorizing lists, sequences, or speeches.', '20-30 min', 'hard', 7),

-- Understanding Techniques
('Feynman Technique', 'understanding', 'Explain the concept in simple language as if teaching a 10-year-old. Identify gaps.', 'If you can''t explain it simply, you don''t understand it. Forces clarity.', 'When a concept feels confusing or abstract.', '15-20 min', 'medium', 10),
('Analogies & Metaphors', 'understanding', 'Connect new concepts to things you already understand deeply.', 'Your brain learns by pattern matching. Analogies create bridges to existing knowledge.', 'For abstract or complex topics.', '10 min', 'medium', 8),
('Concept Mapping', 'understanding', 'Draw diagrams showing how ideas connect. Use arrows, boxes, and labels.', 'Visual representation reveals relationships that linear notes hide.', 'For subjects with interconnected concepts (biology, history).', '20-30 min', 'medium', 9),
('Question Generation', 'understanding', 'After reading, write 5-10 questions that the material answers.', 'Asking questions engages critical thinking. Turns passive reading into active processing.', 'During or after reading assignments.', '10 min', 'easy', 7),

-- Practice Techniques
('Deliberate Practice', 'practice', 'Focus on your weakest areas. Do problems slightly above your current level.', 'Comfort zone = no growth. Struggle = learning. Target your mistakes.', 'For math, physics, coding, music.', '30-60 min', 'hard', 10),
('Interleaving', 'practice', 'Mix different types of problems instead of doing one type repeatedly.', 'Forces your brain to choose strategies. Builds flexibility and transfer.', 'For math, science problem sets.', '30+ min', 'medium', 9),
('Past Papers', 'practice', 'Do old exams under timed conditions. Review mistakes thoroughly.', 'Simulates real pressure. Reveals exam patterns and your weak spots.', '1-2 weeks before exams.', '60-90 min', 'medium', 10),

-- Organization Techniques
('Cornell Notes', 'organization', 'Divide page into: notes (right), cues (left), summary (bottom).', 'Built-in review system. Cues trigger recall. Summary forces synthesis.', 'During lectures or while reading.', 'Ongoing', 'easy', 7),
('Chunking', 'organization', 'Break large topics into 3-5 smaller sub-topics. Study one chunk at a time.', 'Working memory handles ~4 items. Chunking prevents overload.', 'When facing overwhelming amounts of material.', '5 min', 'easy', 8),
('SQ3R Method', 'organization', 'Survey, Question, Read, Recite, Review. Structured reading approach.', 'Active reading beats passive reading. Each step serves a purpose.', 'For textbook chapters.', '45-60 min', 'medium', 7),
('Time Blocking', 'organization', 'Assign specific time slots to specific subjects. Protect the blocks.', 'Prevents decision fatigue. Creates routine. Ensures balanced coverage.', 'For weekly study planning.', 'Ongoing', 'easy', 8);

-- Seed Data: Comprehensive Subject Strategies
insert into study_subjects (name, icon, strategies, color) values
('Math', '🔢', '{
  "how_to_study": "Do problems, not just read solutions. Start easy, build to harder. Redo mistakes until you can solve them without help.",
  "common_traps": [
    "Watching solutions instead of attempting problems",
    "Skipping steps because they seem obvious",
    "Not checking your work",
    "Memorizing formulas without understanding when to use them"
  ],
  "practice_tips": [
    "Do 5 easy problems to build confidence, then 3 hard ones",
    "Explain your process out loud as you solve",
    "Create a mistake log: what you did wrong and why",
    "Redo old tests without looking at answers"
  ],
  "before_exam": "Focus on problem types you struggle with. Do timed practice. Review your mistake log.",
  "when_stuck": "Go back to basics. Break the problem into smaller steps. Try a simpler version first."
}', '#e74c3c'),

('Physics', '⚛️', '{
  "how_to_study": "Understand concepts first, then practice problems. Draw diagrams. Connect formulas to real situations.",
  "common_traps": [
    "Plugging numbers into formulas without understanding",
    "Ignoring units and dimensions",
    "Not drawing free-body diagrams",
    "Memorizing without visualizing"
  ],
  "practice_tips": [
    "Draw every scenario before solving",
    "Explain the physics in words before using math",
    "Check if your answer makes physical sense",
    "Relate problems to everyday experiences"
  ],
  "before_exam": "Review concept maps. Do mixed problem sets. Practice explaining concepts simply.",
  "when_stuck": "Draw it. What forces are acting? What''s conserved? Start with what you know for certain."
}', '#3498db'),

('Chemistry', '🧪', '{
  "how_to_study": "Understand patterns and trends. Use the periodic table as a map. Balance equations by hand.",
  "common_traps": [
    "Memorizing without understanding periodic trends",
    "Skipping balancing practice",
    "Not visualizing molecular structures",
    "Ignoring significant figures"
  ],
  "practice_tips": [
    "Draw Lewis structures for everything",
    "Practice naming compounds daily",
    "Use flashcards for polyatomic ions",
    "Explain reactions in words, not just symbols"
  ],
  "before_exam": "Review reaction types. Practice stoichiometry. Memorize key polyatomic ions.",
  "when_stuck": "Check oxidation states. Is it balanced? What type of reaction is this?"
}', '#9b59b6'),

('Biology', '🧬', '{
  "how_to_study": "Draw diagrams. Make flowcharts for processes. Connect structure to function always.",
  "common_traps": [
    "Passive reading without drawing",
    "Not connecting systems together",
    "Memorizing terms without understanding processes",
    "Ignoring diagrams in textbooks"
  ],
  "practice_tips": [
    "Draw and label diagrams from memory",
    "Create flowcharts for processes (photosynthesis, cell cycle)",
    "Use analogies to remember functions",
    "Teach concepts to someone else"
  ],
  "before_exam": "Review all diagrams. Practice labeling. Explain processes step-by-step.",
  "when_stuck": "What''s the function? How does structure support that? Draw it out."
}', '#27ae60'),

('History', '📜', '{
  "how_to_study": "Create timelines. Ask why and so what. Connect events to causes and effects.",
  "common_traps": [
    "Memorizing dates without context",
    "Not seeing cause-and-effect relationships",
    "Treating events as isolated incidents",
    "Passive reading without analysis"
  ],
  "practice_tips": [
    "Make visual timelines with key events",
    "For each event, ask: Why did this happen? What were the effects?",
    "Compare different time periods or regions",
    "Write practice essays with thesis statements"
  ],
  "before_exam": "Review timelines. Practice writing thesis statements. Know key turning points.",
  "when_stuck": "What came before this? What changed because of it? Who benefited?"
}', '#f39c12'),

('English', '📖', '{
  "how_to_study": "Read actively. Annotate. Analyze themes and literary devices. Write practice paragraphs.",
  "common_traps": [
    "Passive reading without thinking",
    "Not analyzing why the author made choices",
    "Weak thesis statements",
    "Not using textual evidence"
  ],
  "practice_tips": [
    "Highlight and annotate as you read",
    "Write one-sentence summaries of each chapter",
    "Practice writing thesis statements",
    "Find 3 quotes that support each theme"
  ],
  "before_exam": "Review key quotes. Practice essay outlines. Know major themes and symbols.",
  "when_stuck": "What is the author trying to say? What evidence supports this? How does this connect to the theme?"
}', '#8e44ad'),

('Geography', '🌍', '{
  "how_to_study": "Use maps constantly. Understand spatial relationships. Connect physical and human geography.",
  "common_traps": [
    "Memorizing locations without understanding why they matter",
    "Not using maps while studying",
    "Ignoring connections between physical and human geography",
    "Passive reading of case studies"
  ],
  "practice_tips": [
    "Draw maps from memory",
    "For each region, note: climate, resources, population, economy",
    "Create comparison tables for different regions",
    "Use real-world news to understand concepts"
  ],
  "before_exam": "Review all maps. Know key case studies. Practice explaining spatial patterns.",
  "when_stuck": "Where is this? Why is it there? How does location affect this?"
}', '#16a085'),

('Computer Science', '💻', '{
  "how_to_study": "Code by hand. Trace through algorithms step-by-step. Explain logic in plain English.",
  "common_traps": [
    "Only running code, never writing it by hand",
    "Not tracing through code line-by-line",
    "Copying solutions without understanding",
    "Not testing edge cases"
  ],
  "practice_tips": [
    "Write code on paper without running it",
    "Trace variables through each iteration",
    "Explain your algorithm to someone in words",
    "Test with edge cases: empty input, single item, maximum values"
  ],
  "before_exam": "Review common algorithms. Practice writing code by hand. Know time complexity.",
  "when_stuck": "What is the input? What should the output be? What are the steps to get there?"
}', '#2c3e50');
