-- Add this to your Supabase SQL Editor to support Time Management

create table if not exists tasks (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  user_id uuid references auth.users, -- Nullable for dev
  title text not null,
  description text,
  cognitive_type text not null, -- 'Memorize', 'Understand', 'Create', 'Solve', 'Review', 'Write', 'Practice'
  difficulty text not null, -- 'Easy', 'Medium', 'Hard'
  time_estimate int not null, -- in minutes
  emotional_friction text not null, -- 'Low', 'Medium', 'High'
  status text default 'Planned', -- 'Planned', 'Executed', 'Reflected'
  energy_block text, -- 'High', 'Medium', 'Low' (assigned later)
  
  -- Reflection Data
  actual_time int,
  mood text, -- 'Happy', 'Mid', 'Low'
  execution_quality text, -- 'Good', 'Mid', 'Poor'
  notes text
);

-- Disable RLS for now to ensure it works without auth
alter table tasks disable row level security;
alter table tasks alter column user_id drop not null;
